name: NPM Publish

on:
  push:
    tags:
      - 'v*' # Triggers on version tags

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Check version match
        run: |
          TAG_VERSION=$(echo ${{ github.ref_name }} | sed 's/^v//')
          PKG_VERSION=$(node -p "require('./package.json').version")
          LOCK_VERSION=$(node -p "require('./package-lock.json').version")
          
          if [ "$TAG_VERSION" != "$PKG_VERSION" ]; then
            echo "Tag version ($TAG_VERSION) does not match package.json version ($PKG_VERSION)"
            exit 1
          fi
          
          if [ "$PKG_VERSION" != "$LOCK_VERSION" ]; then
            echo "package.json version ($PKG_VERSION) does not match package-lock.json version ($LOCK_VERSION)"
            exit 1
          fi

      - name: Build
        run: npm run build

      - name: Publish to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}